#!/usr/bin/env python3
"""
Email distribution script for Terraform Issues Reports
Sends weekly reports to team members via email
"""

import smtplib
import os
import sys
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

from config import (
    get_team_emails,
    SMTP_SERVER,
    SMTP_PORT,
    SMTP_USERNAME,
    SMTP_PASSWORD,
    EMAIL_FROM,
)

# Report configuration
REPORT_DIR = Path(__file__).parent / "analysis_results"
REPORT_FILE = REPORT_DIR / "terraform_target_services_issues_report_en.md"

# ============================================================================
# EMAIL SENDING LOGIC
# ============================================================================

def read_report_summary(report_path):
    """Extracts summary information from the report."""
    try:
        with open(report_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Extract total issues
        import re
        total_match = re.search(r'\*\*Total Issues Found:\*\* (\d+)', content)
        total_issues = total_match.group(1) if total_match else "N/A"
        
        # Extract categories
        categories = re.findall(r'^## (.+?)$', content, re.MULTILINE)
        
        return {
            'total_issues': total_issues,
            'categories': categories,
            'file_size': f"{os.path.getsize(report_path) / 1024:.1f} KB"
        }
    except Exception as e:
        return {
            'total_issues': 'N/A',
            'categories': [],
            'file_size': 'N/A',
            'error': str(e)
        }


def create_email_body(summary):
    """Creates the email body with summary information."""
    date_str = datetime.now().strftime('%B %d, %Y')
    
    categories_text = '\n'.join([f"   • {cat}" for cat in summary['categories']])
    
    body = f"""Hello Team,

The weekly Terraform Provider Google issues report is ready!

═══════════════════════════════════════════════════════════════

📊 WEEKLY REPORT SUMMARY - {date_str}

   Total Available Issues: {summary['total_issues']}
   Report Size: {summary['file_size']}

📋 Issues by Category:

{categories_text}

═══════════════════════════════════════════════════════════════

The complete report is attached to this email.

This report includes ONLY issues that are:
✓ Currently open
✓ Not assigned to anyone
✓ Not claimed in comments
✓ Not marked as work-in-progress
✓ Relevant to: Load Balancers, Cloud Armor, and Private Service Connect

Each issue includes:
• Issue number and title
• Confidence score
• Direct GitHub URL
• Creation date
• Number of comments

═══════════════════════════════════════════════════════════════

🎯 NEXT STEPS:

1. Review the attached report
2. Choose an issue that interests you
3. Comment on the issue to claim it
4. Start contributing!

═══════════════════════════════════════════════════════════════

Questions? Contact your team lead.

Best regards,
Terraform Issues Analyzer Bot

---
This is an automated weekly report generated by the Terraform Issues Analyzer.
Repository: https://github.com/hashicorp/terraform-provider-google
"""
    
    return body


def send_email(recipients, subject, body, attachment_path):
    """Sends email with attachment to all recipients."""
    
    # Validate SMTP credentials
    if not SMTP_USERNAME or not SMTP_PASSWORD:
        print("❌ ERROR: SMTP credentials not configured!")
        print()
        print("Please set environment variables:")
        print("  export SMTP_USERNAME='your-email@gmail.com'")
        print("  export SMTP_PASSWORD='your-app-password'")
        print()
        print("For Gmail, create an app password at:")
        print("  https://myaccount.google.com/apppasswords")
        return False
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = EMAIL_FROM
        msg['To'] = ', '.join(recipients)
        msg['Subject'] = subject
        
        # Attach body
        msg.attach(MIMEText(body, 'plain', 'utf-8'))
        
        # Attach report file
        with open(attachment_path, 'rb') as f:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(f.read())
            encoders.encode_base64(part)
            
            filename = f"terraform_issues_report_{datetime.now().strftime('%Y-%m-%d')}.md"
            part.add_header('Content-Disposition', f'attachment; filename="{filename}"')
            msg.attach(part)
        
        # Send email
        print(f"📧 Connecting to {SMTP_SERVER}:{SMTP_PORT}...")
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        
        print(f"🔐 Authenticating as {SMTP_USERNAME}...")
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        
        print(f"📨 Sending email to {len(recipients)} recipient(s)...")
        server.send_message(msg)
        server.quit()
        
        print("✅ Email sent successfully!")
        print()
        print(f"Recipients:")
        for email in recipients:
            print(f"   ✓ {email}")
        
        return True
        
    except smtplib.SMTPAuthenticationError:
        print("❌ ERROR: Authentication failed!")
        print()
        print("Please check your SMTP credentials:")
        print(f"   Username: {SMTP_USERNAME}")
        print(f"   Password: {'*' * len(SMTP_PASSWORD) if SMTP_PASSWORD else 'NOT SET'}")
        print()
        print("For Gmail, you need an App Password:")
        print("  1. Enable 2-Factor Authentication")
        print("  2. Generate App Password: https://myaccount.google.com/apppasswords")
        print("  3. Use the 16-character app password")
        return False
        
    except Exception as e:
        print(f"❌ ERROR: Failed to send email: {e}")
        return False


def main():
    """Main execution function."""
    print("=" * 70)
    print("  TERRAFORM ISSUES ANALYZER - EMAIL DISTRIBUTION")
    print("=" * 70)
    print()
    
    # Check if report exists
    if not REPORT_FILE.exists():
        print(f"❌ ERROR: Report file not found!")
        print(f"   Expected: {REPORT_FILE}")
        print()
        print("Please run the analyzer first:")
        print("   python3 script.py")
        sys.exit(1)
    
    print(f"✓ Report found: {REPORT_FILE}")
    print()
    
    # Get team emails from config (environment variable)
    team_emails = get_team_emails()
    
    # Check team emails configuration
    if not team_emails:
        print("⚠️  WARNING: Team emails not configured!")
        print()
        print("Please set the TEAM_EMAILS environment variable:")
        print("   export TEAM_EMAILS='user1@example.com,user2@example.com'")
        print()
        print("Or create a .env file with:")
        print("   TEAM_EMAILS=user1@example.com,user2@example.com")
        print()
        sys.exit(1)
    
    print(f"✓ Team emails configured: {len(team_emails)} recipient(s)")
    for email in team_emails:
        print(f"   • {email}")
    print()
    
    # Read report summary
    print("📊 Reading report summary...")
    summary = read_report_summary(REPORT_FILE)
    print(f"   Total issues: {summary['total_issues']}")
    print(f"   Categories: {len(summary['categories'])}")
    print()
    
    # Create email
    subject = f"Terraform Issues Weekly Report - {datetime.now().strftime('%Y-%m-%d')}"
    body = create_email_body(summary)
    
    # Send email
    print("=" * 70)
    print("SENDING EMAIL")
    print("=" * 70)
    print()
    
    success = send_email(team_emails, subject, body, REPORT_FILE)
    
    print()
    print("=" * 70)
    
    if success:
        print("✅ EMAIL DISTRIBUTION COMPLETED SUCCESSFULLY!")
        print("=" * 70)
        sys.exit(0)
    else:
        print("❌ EMAIL DISTRIBUTION FAILED")
        print("=" * 70)
        sys.exit(1)


if __name__ == "__main__":
    main()